from pyray import *
from raylib import *
from random import randint, uniform
from os.path import join

#GAME INFO
GAME_SPEED = 1.0 
SPRITE_SHEET_TILE_SIZE = 64
WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
GROUND_LEVEL = 400
WINSCORE = 1200
TARGET_FPS = 60
FRAME_SPEED =  TARGET_FPS / 6
MUSIC_VOLUME = .1
BOTTOM_OF_BALL_SPAWN_AREA = 200

#PLAYER INFO
PLAYER_SCALE = 2.0
PLAYER_STARTING_Y = 307
PLAYER_SPEED = 180
PLAYER_DODGE_SPEED = 3 * PLAYER_SPEED
HITBOX_WIDTH_RATIO = .3
HITBOX_HEIGHT_RATIO = 1/3

#BALL INFO
GRAVITY =  240
COEFFICIENT_OF_RESTITUTION = -.97
BALL_HORIZONTAL_SPEED = 120
BALL_VERTICAL_SPEED = 120
MAX_BIG_BALLS = 2
MAX_MEDIUM_BALLS = 4
MAX_SMALL_BALLS = 8
BIG_BALL_RADIUS = 40
MEDIUM_BALL_RADIUS = 20
SMALL_BALL_RADIUS = 10
BIG_BALL_POINTS = 200
MEDIUM_BALL_POINTS = 100
SMALL_BALL_POINTS = 50

#SHOOT INFO
SHOOT_SPEED = 300
SHOOT_DURATION = .105
SHOOT_WIDTH = 64
SHOOT_HEIGHT = 64

#BACKGROUND INFO
BG_FRAME_COUNT = 4


#BRIDGE RENDERING OFFSETS AND DIMENSIONS
BRIDGE_OFFSETX = 70
BRIDGE_LENGTH = 670
BRIDGE_HEIGHT = 80
BRIDGE_OFFSETY = 375

#ANIMATION DURATIONS:
IDLE_DUR = .4
WALK_DUR = .1
DODGE_DUR = .025
SHOOT_ANIM_DUR = .03
DYING_DUR = .3
DODGE_CLOUD_DUR = .05
EYEBALL_BLINK_DUR = .2
DISPLAY_POINTS_DUR = 1.5  
BG_DUR = .15

#COOLDOWNS
DODGE_COOLDOWN = 1.0
SHOOT_COOLDOWN = 1.25     

